import assert from 'node:assert/strict';
import { defaults, validateConfig, encodeConfig, decodeConfig } from '../assets/engagement-state.js';
const customized={style:'halo',cut:'oval',metal:'rose',alloy:'750',carat:1.25,width:2.5,size:58,prongs:6,engraving:'Für immer · A & M ♥'};
assert.deepEqual(decodeConfig(encodeConfig(customized)),customized,'Unicode share-link round trip');
for(const bad of ['', '#bad', '////', btoa('null'),btoa('{"metal":"__proto__","cut":"constructor"}')])assert.deepEqual(decodeConfig(bad),defaults());
assert.equal(validateConfig({...customized,cut:'emerald'}).prongs,4);
assert.equal(validateConfig({...customized,metal:'platinum'}).alloy,'950');
assert.equal(validateConfig({...customized,alloy:'950'}).alloy,'585');
assert.equal(validateConfig({size:1000,carat:-5,width:2.27}).size,70);
assert.equal(validateConfig({size:1000,carat:-5,width:2.27}).carat,.3);
assert.equal(validateConfig({width:2.27}).width,2.3);
assert.deepEqual(validateConfig({size:NaN,carat:null,width:'not a number'}),defaults());
assert.equal(Array.from(validateConfig({engraving:'♥'.repeat(40)}).engraving).length,24);
console.log('CONFIG_OK: round trip, malformed links, limits, alloy and setting constraints');
